.PHONY: test path

# test:
#	nosetests tests -v --nocapture
# -s is equivalent to --nocapture

# apparently you can't set an environment variable of a parent process inside
# a subprocess like Make, but this is the command I want:
#path:
#    export PYTHONPATH="/Users/ajfriend/work/market_eq/"

test:
	ipython -i test/test.py
